insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acid Daggers'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acid Saber'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acid Spitter'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acid Spitter'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Claws and Teeth'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Lash'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Scythes'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Sword'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Talons'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Acidic Vomit'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Barbed Fists and Teeth'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Beam Cannon'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Beam Cannon'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Beam Rifle'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blade of Vanity'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blaster Cannon'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blaster Cannon'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blaster Pistol'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blaster Pistol'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Blunderbuss'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Magnum'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Pistol'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle (Scoped)'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle (Scoped)'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle (Scoped)'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Bolt Rifle (Scoped)'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Boomstick'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chain Blade '), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Chainsaw'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Claws and Fangs'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Claws and Fangs (Possessed Fanatic Only)'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Claws and Teeth (Loyal Animal Only)'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Claws and Teeth (Ro-botic Hound Only)'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Claws and Teeth (Toothy Pet Only)'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Corrupted Blade'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Corrupted Blade'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Corrupted Claws'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Corrupted Claws'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Corrupted Gauntlet'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Crushing Claw'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Custom Twin Blasters'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Custom Twin Blasters'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Disease Expeller'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Disease Expeller'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Drill'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Drill'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Dual Beam Cannon'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Dual Blaster Pistols'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Dual Blaster Pistols'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Dual Power Saber'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Dual Power Saber'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Eggs (Brood Mother only)'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Baton'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Battle Staff'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Hook'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Knife'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Knife'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Knife'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Rod'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Rod'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Saber'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Electrified Scythe'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'EMP Grenade'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fire Blade'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fire Blade'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fire Breath'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fire Breath'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fire Sword'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Firebrands'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Firebrands'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flak Cannon'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flame Cannon'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flame Cannon'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flame Cannon'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flame Cannon'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flame Cannon'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Flamethrower'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Frag Grenade'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fusion Blast Cannon'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Fusion Blaster'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Bolt Repeater'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Bolt Repeater'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Bolt Repeater'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Bolt Repeater'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Bolt Repeater'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Heavy Chain Gun'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Hell Cannon'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Hell Cannon'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Hell Cannon'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Homing Plasma Missiles'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Homing Plasma Missiles'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Huge Daemonic Claws'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Hunting Spear'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Incinerator'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Ion Cannon'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Laser Blaster'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Laser Blaster'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Lightning Cannon'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Lightning Coil'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Line Gun'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Line Gun'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Line Gun'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Massive Talons'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Maul of Corruption'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Moonbeam Whip'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Moonstone Cleaver'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Needle'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Needle Gun'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Needle Rifle'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Nerve Gas Grenade'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Nerve Gas Grenade'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Nerve Gas Grenade'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Nerve Gas Grenade'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pestilence Grenade'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cannon'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cannon'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cannon'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cannon'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cannon'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Cutlass'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Grenade'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Rocket Launcher'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Shotgun'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Shotgun'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Shotgun'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Shotgun'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasma Shotgun'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Plasmid Glove'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Poisoned Blade'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Poisoned Saber'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Poisoned Shuriken'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Claws'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Claws'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Claws'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Gauntlet'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Gauntlet'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Gauntlet'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Gauntlet'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Hammer'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Lance'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Lance'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Saber (LS)'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Saber (LS)'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Saber (LS)'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Saber'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Saber'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Whip'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Power Whip'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Precision Laser Beam'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Carbine'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Carbine'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Handgun'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Handgun'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Jezail'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Jezail'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Jezail (Mech)'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Rifle'), (select id from factions where name = 'Coven Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Pulse Rifle'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Razor Bot Swarm'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Razor Net'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Razor Net'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rivet Gun'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rivet Gun'), (select id from factions where name = 'Machine Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Rocket Launcher'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Searing Probe (TC)'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Searing Probe (TL)'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Searing Razors'), (select id from factions where name = 'The Ancient Machine'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Smoke Grenade'), (select id from factions where name = 'Hunters'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Spike Cannon'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Spike Cannon'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Spore Cannon'), (select id from factions where name = 'The Hive'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Staff of Terror'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Staff of the Marker'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starblast Grenade'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starblast Grenade'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Cannon'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Cannon'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Devastator'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Devastator'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Pistol'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Pistol'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Repeater'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Repeater'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Rifle'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Rifle'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Shotgun'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starfire Shotgun'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starflare Grenade'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Starflare Grenade'), (select id from factions where name = 'Corrupted L’Orani'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'U’rak Warlords'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Terror Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Nomadic Raiders'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Terror Legion'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Continuum Syndicate'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Legion of Mankind'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'The Inquisition'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Intergalactic Marshals'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'Hive Cult'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Subcompact Bolt Gun'), (select id from factions where name = 'The Resistance'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Sunstone Blade'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Sunstone Great-Sword'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Sunstone Saber'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Sunstone Shuriken'), (select id from factions where name = 'L’Orani Empire'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Sword of Horror'), (select id from factions where name = 'Terrors of Abaddon'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Thermal Detonator Grenade'), (select id from factions where name = 'The Dark Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Thermal Detonator Grenade'), (select id from factions where name = 'The Path'));
insert into weapons_factions (weapon_id, faction_id) values ((select id from weapons where name = 'Training Rod'), (select id from factions where name = 'The Path'));
