insert into factions (name, faction_text) values ('Legion of Mankind', '');
insert into factions (name, faction_text) values ('Terror Legion', '');
insert into factions (name, faction_text) values ('The Ancient Machine', '');
insert into factions (name, faction_text) values ('Coven Empire', '');
insert into factions (name, faction_text) values ('Terrors of Abaddon', '');
insert into factions (name, faction_text) values ('L’Orani Empire', '');
insert into factions (name, faction_text) values ('The Hive', '');
insert into factions (name, faction_text) values ('Corrupted L’Orani', '');
insert into factions (name, faction_text) values ('U’rak Warlords', '');
insert into factions (name, faction_text) values ('Hunters', '');
insert into factions (name, faction_text) values ('Nomadic Raiders', '');
insert into factions (name, faction_text) values ('The Path', '');
insert into factions (name, faction_text) values ('The Dark Path', '');
insert into factions (name, faction_text) values ('The Resistance', '');
insert into factions (name, faction_text) values ('Continuum Syndicate', '');
insert into factions (name, faction_text) values ('The Inquisition', '');
insert into factions (name, faction_text) values ('Intergalactic Marshals', '');
insert into factions (name, faction_text) values ('Terror Cult', '');
insert into factions (name, faction_text) values ('Hive Cult', '');
insert into factions (name, faction_text) values ('Machine Cult', '');
