
insert into special_rules (name, level,  text) values ('Inspiring Presence', 1, 'When a soldier with Inspiring Presence 1 executes a Cover Fire, Fire, or Advance Order during the Order Die Phase of a turn, all friendly soldiers within 3” of the soldier’s starting position—including the soldier as well—gain a +1 initiative modifier when executing ranged attacks until the end of the Order Dice Phase.');
insert into special_rules (name, level,  text) values ('Inspiring Presence', 2, 'Soldier must first possess Inspiring Presence 1 to use this skill. Read as Inspiring Presence 1 but increase the range of this skill to 6”.');
insert into special_rules (name, level,  text) values ('Inspiring Presence', 3, 'Soldier must first possess Inspiring Presence 2 to use this skill. Read as Inspiring Presence 2, but instead of gaining an initiative modifier for only ranged attacks, all soldiers gain a +1 bonus to their base initiative value until the end of the phase.');
insert into special_rules (name, level,  text) values ('Natural Leader', 1, 'When a soldier with Natural Leader 1 isassigned an order die, the player may immediately draw 1 more order die for their warband and assign it to any soldier or specialist who is within 6” of the soldier with the Natural Leader skill. Both soldiers may then execute their assigned orders in any sequence of the player’s choosing.');
insert into special_rules (name, level,  text) values ('Natural Leader', 2, 'Soldier must first possess Natural Leader 1 to use this skill. Read as Natural Leader 1, but instead of drawing only 1 additional order die for their warband, the player draws 2 and assigns these additional dice to any soldier and/or specialist who are within 6” of the soldier with the Natural Leader 2 skill.');
insert into special_rules (name, level,  text) values ('Deadeye', 1, 'When a soldier with Deadeye 1 executes any ranged attack, they gain an additional +1 initiative modifier to all ranged attack rolls.');
insert into special_rules (name, level,  text) values ('Deadeye', 2, 'Soldier must first possess Deadeye 1 to use this skill. Read as Deadeye 1, but increase the initiative modifier to +2 when using AoE weapons or grenades.');
insert into special_rules (name, level,  text) values ('Weapons Mastery', 1, 'Soldier must first possess Deadeye 2 to use this skill. In addition to the benefits of Deadeye 2, when assigned a ranged attack order, the soldier with Weapons Mastery may execute two ranged attack orders, one immediately after the other, whether they be the same order type or not, whether they are at the same target or not, and whether they are with the same weapon or not.');
insert into special_rules (name, level,  text) values ('Fighting Instinct', 1, 'When a soldier with Fighting Instinct 1 is engaged in close combat, they gain an additional +1 initiative modifier to their close combat roll.');
insert into special_rules (name, level,  text) values ('Fighting Instinct', 2, 'Soldier must first possess Fighting Instinct 1 to use this skill. Read as Fighting Instinct 1 but increase the initiative modifier to +2.');
insert into special_rules (name, level,  text) values ('Ruthless Nature', 1, 'When a soldier with Ruthless Nature 1, and any friendly soldiers within 12” of the soldier with Ruthless Nature 1, are hit by Cover Fire, they do not execute Down Orders, but remain free to take orders normally.');
insert into special_rules (name, level,  text) values ('Ruthless Nature', 2, 'Soldier must first possess Ruthless Nature 1 to use this skill. Read as Ruthless Nature  1 but increase the range of this skill to 18”.');
insert into special_rules (name, level,  text) values ('Terrifying Aura', 1, 'Soldier must first possess Ruthless Nature 2 to use this skill. In addition to the benefits of Ruthless Nature 2, all enemy soldiers within 12” of the soldier incur a -2 initiative modifier when executing ranged attacks or fighting in close combat.');
insert into special_rules (name, level,  text) values ('Psychic Prowess', 1, 'When a soldier with Psychic Prowess attempts to cast a psychic ability, they add +1 initiative modifier to their total power level roll.');
insert into special_rules (name, level,  text) values ('Psychic Prowess', 2, 'Soldier must first possess Psychic Prowess 1 to use this skill. Read as Psychic Prowess 1, but increase the initiative modifier to +2.');
insert into special_rules (name, level,  text) values ('Telekinetic Mastery', 1, 'Soldier must first possess Psychic Prowess 2 to use this skill. In addition to the benefits of Psychic Prowess 2, once per game the soldier may automatically cast one psychic ability from their available abilities. No dice roll necessary, and this particular cast cannot be blocked nor countered.');
insert into special_rules (name, level,  text) values ('Stealth', 1, 'When a soldier with Stealth 1 must make a dodge roll, apply an additional +2 initiative modifier to the total.');
insert into special_rules (name, level,  text) values ('Stealth', 2, 'Soldier must first possess Stealth 1 to use this skill. In addition to the benefits of Stealth 1, when this soldier executes a Down Order and is against any type of cover, they cannot be directly targeted by a Fire or Focus Fire order.');
insert into special_rules (name, level,  text) values ('Field Medicine', 1, 'Field Medicine. When a soldier with Field Medicine executes a Down Order, instead of only using one-time use relics on their own self, they may also use a relic and apply its effect on any friendly soldier or specialist but not a mech—within 3” of the able soldier’s position.  Additionally, when the soldier executes a Mend Order, they always regain +3 health value, up to their initial maximum, with no D6 roll required. This soldier may also transfer the effect of their Mend Order to any one friendly soldier or specialist—but not mech—within 3” of their position.');
insert into special_rules (name, level,  text) values ('Field Mechanic', 1, 'When a soldier with Field Mechanic executes a Mend Order, they may transfer the effect of their Mend Order to any one friendly specialist marked (Mech) within 3” of their position.');
insert into special_rules (name, level,  text) values ('Tough Skin', 1, 'Any time a soldier with Tough Skin must apply damage, the soldier temporarily gains +1 armor value when calculating the total damage against their armor.');

