

insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'Legion of Mankind'), 'Sergeant'    , 5 , 5 ,10, 5,  0, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Legion of Mankind'), 'Corporal'   , 5 , 4 ,10, 4,  14, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Legion of Mankind'), 'Lance-Corporal' , 5 , 3, 8, 3,  10, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Legion of Mankind'), 'Private', 5 , 3, 8, 2,  8, false, false, false);

insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Scout'  , 6 , 3, 8, 1,  8, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Engineer'   , 4 , 3, 8, 4,  15, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Medic', 5 , 3, 8, 2,  10, false, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Chaplain'  , 5 , 4 ,8, 2,  12, false, true, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Assault Mech'   , 7 , 4 ,10, 5,  18, true, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Legion of Mankind'), 'Support Mech' , 5 , 4 ,12, 6,  20, true, false, true);




insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'Terror Legion'), 'Terror Sergeant' , 4 , 5 ,10, 5, 0 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terror Legion'), 'Terror Veteran Guard', 4 , 4 ,10, 3,  15 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terror Legion'), 'Terror Guard', 4 , 3, 8, 3,  12, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terror Legion'), 'Slave to Terror', 6 , 2, 8, 1,  7 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terror Legion'), 'Doomsayer', 4 , 4 ,10, 3,  16 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terror Legion'), 'Corrupted Apothecary', 4 , 3, 8, 2,  10 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terror Legion'), 'Warlock' , 4 , 5 ,8, 2,  14 , false, true, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terror Legion'), 'Terror Engine' , 6 , 4, 10, 4,  18, true, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terror Legion'), 'Terror Mech' , 6 , 4, 12, 5,  20, true, false, true);


insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'Terrors of Abaddon'), 'Terror Principality' , 6 , 5 ,12, 0, 0 , false, true, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terrors of Abaddon'), 'Champion of Horror', 6 , 4, 10, 0,  14 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terrors of Abaddon'), 'Champion of Lust', 6 , 4, 10, 0,  14, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terrors of Abaddon'), 'Champion of Chaos' , -999 , -999 ,10, 0,  12 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Terrors of Abaddon'), 'Terror', 5 , 3, 8, 0,  10 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terrors of Abaddon'), 'Hell Hound', 6 , 2, 8, 0,  8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terrors of Abaddon'), 'Changeling', 6 , -999 ,10, 0,  10 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terrors of Abaddon'), 'Foul Beast', 5 , 4, 12, 0,  12 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terrors of Abaddon'), 'Ancient Terror Engine' , 5 , 4, 12, 0,  18 , true, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Terrors of Abaddon'), 'Advent of Abaddon' , 5 , 5 ,20, 0,  28, false, true, true);

insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'The Hive'), 'Taskmaster', 6 , 5 ,12, 4, 0 , false, true, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Hive'), 'Drone X', 6 , -4  ,8, 3,  8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Hive'), 'Drone Y', 6 , -3 ,7, 3,  8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Hive'), 'Drone Z', 7 , -3 ,7, 2,  8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Hive'), 'Harvester', 7 , -4  ,8, 3,  12 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Hive'), 'Warrior X', 6 , -4  ,10, 4,  14 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Hive'), 'Warrior Y', 6 , -4  ,10, 4,  14 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Hive'), 'Reaper' , 6 , -4  ,10, 5,  16 , false, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Hive'), 'Brood Mother', 4 , 5 ,18, 2,  20, false, true, true);

insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'The Ancient Machine'), 'Ancient Seer' , 4 ,6 ,12 ,-999 , 0 , false, true, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Ancient Machine'), 'Bot Mk2', 4 , 4, 10 ,-999, 13 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Ancient Machine'), 'Bot Mk1', 4, 3, 10 ,-999, 10 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'The Ancient Machine'), 'Razor Bot Swarm', 6 , 2, 8 ,-999 ,8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Ancient Machine'), 'Shock-trooper Bot', 6 , 4, 8 ,-999, 12, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Ancient Machine'), 'Heavy Support Bot', 4 , 3, 12 ,-999, 13, false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Ancient Machine'), 'Ancient Soothsayer', 4 , 5 ,8 ,-999, 15 , false, true, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Ancient Machine'), 'Razor Bot Mother', 6 , 4, 12 ,-999, 17 , true, false, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'The Ancient Machine'), 'War Machine', 4 , 4, 14 ,-999, 20, true, false, true);

insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Alpha'), (select id from factions where name = 'Coven Empire'), 'Coven Sergeant' , 5 , 5 ,9, 5, 0 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Coven Empire'), 'Coven Veteran Trooper', 5 , 5 ,9, 4,  16 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Coven Empire'), 'Coven Trooper', 5 , 4, 7, 3,  12 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Soldier'), (select id from factions where name = 'Coven Empire'), 'Coven Serf', 5 , 3, 7, 2,  8 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Coven Empire'), 'Coven Hover Drone' ,8 , -1 ,7, 1,  7 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Coven Empire'), 'Coven Scout', 6 , 3, 9, 1,  10 , false, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Coven Empire'), 'Coven Battle Priest' , 5 , 5 ,9, 2,  13, false, true, true);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Coven Empire'), 'Coven Stealth Suit' , 5 , 5 ,9, 4,  17, true, false, false);
insert into soldiers (solider_type_id, faction_id, name, move, initiative, health, armor, cost, mech, psychic, unique_soldier) values ((select id from soldier_types where type = 'Specialist'), (select id from factions where name = 'Coven Empire'), 'Coven Battle Mech' , 5 , 4 ,10 ,6 ,20, true, false, true);

